language: php

php:
 # - 5.3
  - 5.4
#  - 5.5

env:
  - DB=apc
  - DB=memcache

before_script:
 
  - sh -c "if [ '$DB' = 'apc' ]; then echo 'extension=apc.so' >> `php --ini | grep 'Loaded Configuration' | sed -e 's|.*:\s*||'`; fi"
  - sh -c "if [ '$DB' = 'apc' ]; then echo 'apc.enable_cli=1' >> `php --ini | grep 'Loaded Configuration' | sed -e 's|.*:\s*||'`; fi"
  - sh -c "if [ '$DB' = 'memcache' ]; then sudo pecl install memcached-2.0.1; /usr/bin/memcached -d; fi"
  - phpenv rehash
  - composer install --dev --prefer-source


script:
  - phpunit --coverage-text --configuration phpunit.xml.dist

